"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.UptimeTimeseriesResolver = exports.StoredDataTimeseriesResolver = exports.ServedDataTimeseriesResolver = exports.QueriesCountTimeseriesResolver = exports.DelegatorsTimeseriesResolver = exports.DelegationsTimeseriesResolver = exports.UniqueOperatorsTimeseriesResolver = exports.ActiveWorkersTimeseriesResolver = exports.RewardTimeseriesResolver = exports.AprTimeseriesResolver = exports.WorkersSummaryResolver = exports.SquidStatusResolver = exports.DaysUptimeResolver = void 0;
require("reflect-metadata");
var daysUptime_1 = require("./daysUptime");
Object.defineProperty(exports, "DaysUptimeResolver", { enumerable: true, get: function () { return daysUptime_1.DaysUptimeResolver; } });
var squidStatus_1 = require("./squidStatus");
Object.defineProperty(exports, "SquidStatusResolver", { enumerable: true, get: function () { return squidStatus_1.SquidStatusResolver; } });
var summary_1 = require("./summary");
Object.defineProperty(exports, "WorkersSummaryResolver", { enumerable: true, get: function () { return summary_1.WorkersSummaryResolver; } });
var timeseries_1 = require("./timeseries");
Object.defineProperty(exports, "AprTimeseriesResolver", { enumerable: true, get: function () { return timeseries_1.AprTimeseriesResolver; } });
Object.defineProperty(exports, "RewardTimeseriesResolver", { enumerable: true, get: function () { return timeseries_1.RewardTimeseriesResolver; } });
Object.defineProperty(exports, "ActiveWorkersTimeseriesResolver", { enumerable: true, get: function () { return timeseries_1.ActiveWorkersTimeseriesResolver; } });
Object.defineProperty(exports, "UniqueOperatorsTimeseriesResolver", { enumerable: true, get: function () { return timeseries_1.UniqueOperatorsTimeseriesResolver; } });
Object.defineProperty(exports, "DelegationsTimeseriesResolver", { enumerable: true, get: function () { return timeseries_1.DelegationsTimeseriesResolver; } });
Object.defineProperty(exports, "DelegatorsTimeseriesResolver", { enumerable: true, get: function () { return timeseries_1.DelegatorsTimeseriesResolver; } });
Object.defineProperty(exports, "QueriesCountTimeseriesResolver", { enumerable: true, get: function () { return timeseries_1.QueriesCountTimeseriesResolver; } });
Object.defineProperty(exports, "ServedDataTimeseriesResolver", { enumerable: true, get: function () { return timeseries_1.ServedDataTimeseriesResolver; } });
Object.defineProperty(exports, "StoredDataTimeseriesResolver", { enumerable: true, get: function () { return timeseries_1.StoredDataTimeseriesResolver; } });
Object.defineProperty(exports, "UptimeTimeseriesResolver", { enumerable: true, get: function () { return timeseries_1.UptimeTimeseriesResolver; } });
//# sourceMappingURL=index.js.map