export const portalRegistryAbi = [
  { type: 'constructor', inputs: [], stateMutability: 'nonpayable' },
  {
    type: 'function',
    name: 'DEFAULT_ADMIN_ROLE',
    inputs: [],
    outputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'MAX_CLUSTERS_PER_OWNER',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'MAX_PORTALS_PER_CLUSTER',
    inputs: [],
    outputs: [{ name: '', type: 'uint8', internalType: 'uint8' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'PAUSER_ROLE',
    inputs: [],
    outputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'SQD',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'contract IERC20' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'UPGRADE_INTERFACE_VERSION',
    inputs: [],
    outputs: [{ name: '', type: 'string', internalType: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'addPortal',
    inputs: [
      { name: 'clusterId', type: 'bytes32', internalType: 'bytes32' },
      { name: 'peerId', type: 'bytes', internalType: 'bytes' },
      { name: 'metadata', type: 'string', internalType: 'string' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'addressToClusterId',
    inputs: [{ name: '', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'allClusterIds',
    inputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'clusterCount',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'factory',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getActiveClusters',
    inputs: [
      { name: 'offset', type: 'uint256', internalType: 'uint256' },
      { name: 'limit', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [
      { name: 'clusterIds', type: 'bytes32[]', internalType: 'bytes32[]' },
      {
        name: 'clusters',
        type: 'tuple[]',
        internalType: 'struct IPortalRegistry.Cluster[]',
        components: [
          { name: 'clusterAddress', type: 'address', internalType: 'address' },
          { name: 'operator', type: 'address', internalType: 'address' },
          { name: 'totalStaked', type: 'uint256', internalType: 'uint256' },
          { name: 'registeredAt', type: 'uint256', internalType: 'uint256' },
          { name: 'active', type: 'bool', internalType: 'bool' },
          { name: 'metadata', type: 'string', internalType: 'string' },
          {
            name: 'portals',
            type: 'tuple[]',
            internalType: 'struct IPortalRegistry.Portal[]',
            components: [
              { name: 'peerId', type: 'bytes', internalType: 'bytes' },
              { name: 'metadata', type: 'string', internalType: 'string' },
              { name: 'addedAt', type: 'uint64', internalType: 'uint64' },
            ],
          },
        ],
      },
      { name: 'totalActive', type: 'uint256', internalType: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getCluster',
    inputs: [{ name: 'clusterId', type: 'bytes32', internalType: 'bytes32' }],
    outputs: [
      {
        name: '',
        type: 'tuple',
        internalType: 'struct IPortalRegistry.Cluster',
        components: [
          { name: 'clusterAddress', type: 'address', internalType: 'address' },
          { name: 'operator', type: 'address', internalType: 'address' },
          { name: 'totalStaked', type: 'uint256', internalType: 'uint256' },
          { name: 'registeredAt', type: 'uint256', internalType: 'uint256' },
          { name: 'active', type: 'bool', internalType: 'bool' },
          { name: 'metadata', type: 'string', internalType: 'string' },
          {
            name: 'portals',
            type: 'tuple[]',
            internalType: 'struct IPortalRegistry.Portal[]',
            components: [
              { name: 'peerId', type: 'bytes', internalType: 'bytes' },
              { name: 'metadata', type: 'string', internalType: 'string' },
              { name: 'addedAt', type: 'uint64', internalType: 'uint64' },
            ],
          },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getClusterByAddress',
    inputs: [{ name: 'clusterAddress', type: 'address', internalType: 'address' }],
    outputs: [
      {
        name: '',
        type: 'tuple',
        internalType: 'struct IPortalRegistry.Cluster',
        components: [
          { name: 'clusterAddress', type: 'address', internalType: 'address' },
          { name: 'operator', type: 'address', internalType: 'address' },
          { name: 'totalStaked', type: 'uint256', internalType: 'uint256' },
          { name: 'registeredAt', type: 'uint256', internalType: 'uint256' },
          { name: 'active', type: 'bool', internalType: 'bool' },
          { name: 'metadata', type: 'string', internalType: 'string' },
          {
            name: 'portals',
            type: 'tuple[]',
            internalType: 'struct IPortalRegistry.Portal[]',
            components: [
              { name: 'peerId', type: 'bytes', internalType: 'bytes' },
              { name: 'metadata', type: 'string', internalType: 'string' },
              { name: 'addedAt', type: 'uint64', internalType: 'uint64' },
            ],
          },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getClusterIdByAddress',
    inputs: [{ name: 'clusterAddress', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getClusterIdByPeerId',
    inputs: [{ name: 'peerId', type: 'bytes', internalType: 'bytes' }],
    outputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getClusterPortals',
    inputs: [{ name: 'clusterId', type: 'bytes32', internalType: 'bytes32' }],
    outputs: [
      {
        name: '',
        type: 'tuple[]',
        internalType: 'struct IPortalRegistry.Portal[]',
        components: [
          { name: 'peerId', type: 'bytes', internalType: 'bytes' },
          { name: 'metadata', type: 'string', internalType: 'string' },
          { name: 'addedAt', type: 'uint64', internalType: 'uint64' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getClustersPaginated',
    inputs: [
      { name: 'offset', type: 'uint256', internalType: 'uint256' },
      { name: 'limit', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [
      { name: 'clusterIds', type: 'bytes32[]', internalType: 'bytes32[]' },
      {
        name: 'clusters',
        type: 'tuple[]',
        internalType: 'struct IPortalRegistry.Cluster[]',
        components: [
          { name: 'clusterAddress', type: 'address', internalType: 'address' },
          { name: 'operator', type: 'address', internalType: 'address' },
          { name: 'totalStaked', type: 'uint256', internalType: 'uint256' },
          { name: 'registeredAt', type: 'uint256', internalType: 'uint256' },
          { name: 'active', type: 'bool', internalType: 'bool' },
          { name: 'metadata', type: 'string', internalType: 'string' },
          {
            name: 'portals',
            type: 'tuple[]',
            internalType: 'struct IPortalRegistry.Portal[]',
            components: [
              { name: 'peerId', type: 'bytes', internalType: 'bytes' },
              { name: 'metadata', type: 'string', internalType: 'string' },
              { name: 'addedAt', type: 'uint64', internalType: 'uint64' },
            ],
          },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getComputationUnits',
    inputs: [{ name: 'clusterId', type: 'bytes32', internalType: 'bytes32' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getOperatorClusters',
    inputs: [{ name: 'operator', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'bytes32[]', internalType: 'bytes32[]' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getPortalCount',
    inputs: [{ name: 'clusterId', type: 'bytes32', internalType: 'bytes32' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getRoleAdmin',
    inputs: [{ name: 'role', type: 'bytes32', internalType: 'bytes32' }],
    outputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'grantRole',
    inputs: [
      { name: 'role', type: 'bytes32', internalType: 'bytes32' },
      { name: 'account', type: 'address', internalType: 'address' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'hasRole',
    inputs: [
      { name: 'role', type: 'bytes32', internalType: 'bytes32' },
      { name: 'account', type: 'address', internalType: 'address' },
    ],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'initialize',
    inputs: [
      { name: '_sqd', type: 'address', internalType: 'address' },
      { name: '_minStake', type: 'uint256', internalType: 'uint256' },
      { name: '_mana', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'isCluster',
    inputs: [{ name: 'clusterAddress', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'mana',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'minStake',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'multicall',
    inputs: [{ name: 'data', type: 'bytes[]', internalType: 'bytes[]' }],
    outputs: [{ name: 'results', type: 'bytes[]', internalType: 'bytes[]' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'ownerClusters',
    inputs: [
      { name: '', type: 'address', internalType: 'address' },
      { name: '', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
    stateMutability: 'view',
  },
  { type: 'function', name: 'pause', inputs: [], outputs: [], stateMutability: 'nonpayable' },
  {
    type: 'function',
    name: 'paused',
    inputs: [],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'peerIdToCluster',
    inputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
    outputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'proxiableUUID',
    inputs: [],
    outputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'registerCluster',
    inputs: [
      { name: 'clusterAddress', type: 'address', internalType: 'address' },
      { name: 'operator', type: 'address', internalType: 'address' },
      { name: 'metadata', type: 'string', internalType: 'string' },
    ],
    outputs: [{ name: 'clusterId', type: 'bytes32', internalType: 'bytes32' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'removePortal',
    inputs: [
      { name: 'clusterId', type: 'bytes32', internalType: 'bytes32' },
      { name: 'portalIndex', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'renounceRole',
    inputs: [
      { name: 'role', type: 'bytes32', internalType: 'bytes32' },
      { name: 'callerConfirmation', type: 'address', internalType: 'address' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'revokeRole',
    inputs: [
      { name: 'role', type: 'bytes32', internalType: 'bytes32' },
      { name: 'account', type: 'address', internalType: 'address' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setClusterMetadata',
    inputs: [
      { name: 'clusterId', type: 'bytes32', internalType: 'bytes32' },
      { name: 'metadata', type: 'string', internalType: 'string' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setClusterMetadataByPool',
    inputs: [{ name: 'metadata', type: 'string', internalType: 'string' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setFactory',
    inputs: [{ name: '_factory', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setMana',
    inputs: [{ name: '_mana', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setMinStake',
    inputs: [{ name: '_minStake', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setPortalMetadata',
    inputs: [
      { name: 'clusterId', type: 'bytes32', internalType: 'bytes32' },
      { name: 'portalIndex', type: 'uint256', internalType: 'uint256' },
      { name: 'metadata', type: 'string', internalType: 'string' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'stake',
    inputs: [{ name: 'amount', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'supportsInterface',
    inputs: [{ name: 'interfaceId', type: 'bytes4', internalType: 'bytes4' }],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'tryMulticall',
    inputs: [{ name: 'data', type: 'bytes[]', internalType: 'bytes[]' }],
    outputs: [
      { name: 'successes', type: 'bool[]', internalType: 'bool[]' },
      { name: 'results', type: 'bytes[]', internalType: 'bytes[]' },
    ],
    stateMutability: 'nonpayable',
  },
  { type: 'function', name: 'unpause', inputs: [], outputs: [], stateMutability: 'nonpayable' },
  {
    type: 'function',
    name: 'unstake',
    inputs: [
      { name: 'provider', type: 'address', internalType: 'address' },
      { name: 'amount', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'updateClusterOperator',
    inputs: [{ name: 'newOperator', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'upgradeToAndCall',
    inputs: [
      { name: 'newImplementation', type: 'address', internalType: 'address' },
      { name: 'data', type: 'bytes', internalType: 'bytes' },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
] as const;
